config/routes.rb
Rails.application.routes.draw do

devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
   sessions:      'users/sessions',
   passwords:     'users/passwords',
   registrations: 'users/registrations'
}
	root 'users/products#top'
	get '/admins/top', to:'admins/products#top'
	get '/users', to:'users#show', as:'users'
	get '/order/set_address', to:'users/orders#set_address'
	get '/order/confirmation/:shipping_address_id', to:'users/orders#new', as:'order_confirmation'
	post '/order', to:'users/orders#create'
	get '/order/complete', to:'users/orders#show'
	get '/order_address/new', to:'users/shipping_addresses#new_when_order'
	post '/order_address', to:'users/shipping_addresses#create_when_order'
	get 'search', to: 'products#search', as: :search
	post '/admins/products/new/artist_create', to: 'admins/products#artist_create'
	post '/admins/products/new/label_create', to: 'admins/products#label_create'
	post '/admins/products/new/category_create', to: 'admins/products#category_create'
	post '/admins/products/new/create', to: 'admins/products#create'
	# patch '/admins/products/new/artist_update', to: 'admins/products#artist_update'
	# patch '/admins/products/new/label_update', to: 'admins/products#label_update'
	# patch '/admins/products/new/category_update', to: 'admins/products#category_update'
	# patch '/admins/products/new/update', to: 'admins/products#update'
	# post '/users/products', to:'carts#create'
	namespace :users do
		resources :shipping_addresses
		resources :products, only: [:index, :show]
		get 'search', to: 'products#search'
	end
	resources :carts, only: [:index, :create, :update, :destroy]
	namespace :admins do
		resources :users, only: [:index, :show, :edit ,:update, :destroy]
		resources :products
		resources :orders, only: [:index, :update]
	end

	devise_scope :user do
    	get 'cart/sign_in/:product_id/:number', to: 'users/sessions#new'
  	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  enum gender: {
  	男:1,女:2
  }

	enum prefectures: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
   def full_name
   	[last_name, first_name].join("")
   end


  has_many :shipping_addresses
  has_many :orders
  has_many :carts
  has_many :products, through: :carts
  acts_as_paranoid

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :birthday, presence: true
  validates :gender, presence: true
  validates :phone_number, presence: true
  validates :phone_number, length: { in:10..15 }
  validates :post_number, presence: true
  validates :post_number, length: { in:7..8 }
  validates :prefectures, presence: true
  validates :city, presence: true
  validates :block, presence: true

  #self.abstract_class = true

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

   def show
   	   @user = User.find(params[:id])
       @orders = Order.where(user_id: @user)
   end

   def index
   	   @search = User.page(params[:page]).ransack(params[:q])
   	   @users = @search.result
   end

   def edit
       @user = User.find(params[:id])
   end

   def update
       user = User.find(params[:id])
       user.update(user_params)
       logger.debug user.errors.inspect
       redirect_to admins_user_path
   end

   def destroy
       #User.with_deleted.find_by(id: 1).restore
   	   user = User.find(params[:id])
   	   user.destroy
   	   redirect_to admins_users_path
   end


   private
   def user_params
		params.require(:user).permit(:full_name, :last_name, :first_name, :last_name_kana, :first_name_kana, :birthday, :gender, :phone_number, :email, :post_number, :prefectures, :city, :block, :password, :password_confirmation)
   end

   private
   def order_params
    params.require(:order).permit(:shipping_status)
   end

   protected

def update_resource(resource, params)
 resource.update_without_password(params)
end

 end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
	include ApplicationHelper
	before_action :authenticate_user!

	def set_address
		@shipping_addresses = ShippingAddress.where(user_id: current_user.id)
	end

	def new
		@carts = Cart.where(user_id: current_user.id)
		#アカウントの登録住所を配送先にする場合
		if params[:shipping_address_id] == "0"
			@shipping_address = ShippingAddress.new
			@shipping_address.last_name = current_user.last_name
			@shipping_address.first_name = current_user.first_name
			@shipping_address.post_number = current_user.post_number
			@shipping_address.prefectures = current_user.prefectures
			@shipping_address.city = current_user.city
			@shipping_address.block = current_user.block
		else
			#url直打ちを弾く
			shipping_addresses = ShippingAddress.where(user_id: current_user.id)
			shipping_ids = []
			shipping_addresses.each do |f|
				shipping_ids.push(f.id)
			end
			if shipping_ids.include?(params[:shipping_address_id].to_i)
				@shipping_address = ShippingAddress.find(params[:shipping_address_id])
			else
				render body: "forbidden"
			end
		end
		session[:shipping_address_id] = params[:shipping_address_id]
	end

	def create
		#アカウントの登録住所を配送先にする場合
		shipping_address_id = session[:shipping_address_id]
		if shipping_address_id == "0"
			shipping_address = ShippingAddress.new
			shipping_address.last_name = current_user.last_name
			shipping_address.first_name = current_user.first_name
			shipping_address.post_number = current_user.post_number
			shipping_address.prefectures = current_user.prefectures
			shipping_address.city = current_user.city
			shipping_address.block = current_user.block
		else
			shipping_address = ShippingAddress.find(shipping_address_id)
		end

		carts = Cart.where(user_id: current_user.id)
		if carts.none?{ |cart| cart.number > cart.product.stock }
			#Order作成
			order = Order.new
			order.shipping_name = full_name(shipping_address)
			order.shipping_post_number = shipping_address.post_number
			order.shipping_address = full_address(shipping_address)
			order.user_id = current_user.id
			order.save

			#BuyProducts作成
			carts.each do |cart|
				buy_product = BuyProduct.new
				buy_product.product_id = cart.product_id
				buy_product.buy_title = cart.product.title
				buy_product.buy_price = cart.product.price
				buy_product.buy_number = cart.number
				buy_product.order_id = order.id
				buy_product.save

				#在庫減らす
				product = cart.product
				product.stock -= cart.number
				product.save

				#カート削除
				cart.delete
			end
			redirect_to order_complete_path
		else
			carts.each do |cart|
				if cart.number > cart.product.stock
					flash["notice#{cart.id}"] = "「#{cart.product.title}」の枚数を#{cart.product.stock}枚以下に設定してください。"
				end
			end
			redirect_to carts_path
		end
	end

	def show
	end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/products_controller.rb
class Users::ProductsController < ApplicationController

  def top
    @q = Product.includes(:artist).ransack(params[:q])
    @products = @q.result(distinct: true)
  end

  def index
  	@q = Product.page(params[:page]).includes(discs: :songs).ransack(params[:q])
    @products = @q.result(distinct: true).includes(:artist, :category)
    @categories = Category.all
  end

  def search
    @q = Product.search(search_params)
    @products = @products.page(params[:page]).per(5)
    @products = @q.result(distinct: true)
  end

  def show
    @product = Product.find(params[:id])
    p "---------------------"
    p params
    p params[:id]
    p "---------------------"
   	@cart = Cart.new
  end

  private
  def search_params
    params.require(:q).permit!
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]





   def create
      build_resource(sign_up_params)
      resource.save
      yield resource if block_given?
      if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
      else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
      end
   end

   protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  # before_action :configure_sign_in_params, only: [:create]
  def new
    self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    yield resource if block_given?
    session[:product_id] = params[:product_id]
    session[:number] = params[:number]
    respond_with(resource, serialize_options(resource))
  end

  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    if session[:product_id].nil?
      respond_with resource, location: after_sign_in_path_for(resource)
    else
      cart = Cart.new(product_id:session[:product_id], user_id: current_user.id, number: session[:number])
      cart.save
      logger.debug cart.errors.inspect
      session[:product_id] = nil
      session[:number] = nil
      respond_with resource, location: after_sign_in_before_cart_path_for(resource)
    end
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/shipping_addresses_controller.rb
class Users::ShippingAddressesController < ApplicationController
	def new
		@shipping_address = ShippingAddress.new
	end

	def create
		shipping_address = ShippingAddress.new(shipping_address_params)
		shipping_address.user_id = current_user.id
		shipping_address.save
		redirect_to users_shipping_addresses_path
	end

	def index
		@shipping_addresses = ShippingAddress.where(user_id: current_user.id)
	end

	def edit
		@shipping_address = ShippingAddress.find(params[:id])
	end

	def update
		shipping_address = ShippingAddress.find(params[:id])
		shipping_address.update(shipping_address_params)
		redirect_to users_shipping_addresses_path
	end

	def destroy
		shipping_address = ShippingAddress.find(params[:id])
        shipping_address.destroy
        redirect_to users_shipping_addresses_path
	end

	def new_when_order
		@shipping_address = ShippingAddress.new
	end

	def create_when_order
		shipping_address = ShippingAddress.new(shipping_address_params)
		shipping_address.user_id = current_user.id
		shipping_address.save
		redirect_to order_confirmation_path(shipping_address.id)
	end

	private
	def shipping_address_params
		params.require(:shipping_address).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_number, :prefectures, :city, :block, :phone_number)
	end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!


	def new
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
		user.update(user_params)
		redirect_to users_path

	end

	def create
		user = User.new(user_params)
		user.save
	end


	def show
		@user = User.find(current_user.id)
		@orders = Order.where(user_id: current_user.id)
	end

	def destroy
		user = User.find(params[:id])
		user = destroy
		redirect_to new_user_session_path
	end

    private
	def user_params
		params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :birthday, :gender, :phone_number, :email_adress, :post_number, :prefectures, :city, :block, :password, :password_confirmation)
	end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/orders_helper.rb
module Users::OrdersHelper
end

app/helpers/users/products_helper.rb
module Users::ProductsHelper
end

app/helpers/users/shipping_addresses_helper.rb
module Users::ShippingAddressesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/edit.html.erb
<main>
  <div class="container">
    <div class="text-white">
      <h3 class="title">ユーザー情報の編集</h3>
        <%= form_for @user,:url => {:action => :update} do |f| %>
          <div class="row">
            <div class="col-md-5 right">
              <div class="field ">
                <%= f.label :名前（姓） %><br />
                <%= f.text_field :last_name, autofocus: true%>
              </div>
              <div class="field ">
                <%= f.label :名前（名） %><br />
                <%= f.text_field :first_name, autofocus: true%>
              </div>
              <div class="field ">
                <%= f.label :名前（姓・カナ） %><br />
                <%= f.text_field :last_name_kana, autofocus: true%>
              </div>
              <div class="field ">
                <%= f.label :名前（名・カナ） %><br />
                <%= f.text_field :first_name_kana, autofocus: true%>
              </div>
              <div class="birth_date_field gap-top">
                <%= f.label :生年月日 %>
                <%= raw sprintf(
                f.date_select(:birthday, use_month_numbers: true, start_year: 1930, end_year: (Time.now.year - 18), default: Date.new(1989, 1, 1), date_separator: '%s'),'年 ', '月 ') + '日' %>
              </div>
              <div class="field" style="width: 180px; margin-left: 265px;">
                <%= f.label :性別 %><br />
                <%= f.select :gender, User.genders.keys, {prompt: '選択してください'}, class: 'form-control' %>
              </div>
              <div class="field ">
                <%= f.label :電話番号 %><br />
                <%= f.text_field :phone_number, autofocus: true%>
              </div>
              <div class="field ">
                <%= f.label :メールアドレス %><br />
                <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
              </div>
            </div>

            <div class="col-md-4 right">
              <div class="field text-white">
                <%= f.label :郵便番号 %><br />
                <%= f.text_field :post_number, autofocus: true%>
              </div>
              <div class="field text-white gender-width" style="margin-left: 170px;">
                <%= f.label :都道府県 %><br />
                <%= f.select :prefectures, User.prefectures.keys, {prompt: '選択してください'}, class: 'form-control'%>
              </div>
              <div class="field text-white">
                <%= f.label :市区町村 %><br />
                <%= f.text_field :city, autofocus: true%>
              </div>
              <div class="field text-white">
                <%= f.label :番地・建物名 %><br />
                <%= f.text_field :block, autofocus: true%>
              </div>
              <div class="field text-white ">
                <%= f.label :パスワード %>
                  <br />
                  <%= f.password_field :password, value: @user.password %>
              </div>
              <div class="field text-white">
                <%= f.label :パスワード確認 %><br />
                <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div style="margin:  auto !important;">
              <%= f.submit "変更を保存", class: "btn btn-success" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</main>

app/views/admins/users/index.html.erb
<main>
	<div class="container text-light">
			<h1 class="user-title text-center">ユーザー一覧</h1>

        <%= search_form_for(@search, url: admins_users_path, method: :get) do |f| %>
            <%= f.text_field :email_or_phone_number_or_last_name_or_first_name_cont %>
            <%= f.submit "検索", class: "btn btn-danger ml-4" %>
        <% end %>
      <table class="table table-hover text-center mt-4" id="table-center">
        <tr class="bg-light text-dark">
          <td>名前</td>
          <td>都道府県</td>
          <td>メールアドレス</td>
          <td>電話番号</td>
          <td>編集</td>
          <td>削除</td>
        </tr>
        <% @users.order("id desc").each do |user| %>
          <tr>
            <td><%= link_to full_name(user), admins_user_path(user.id) %></td>
            <td><%= full_address(user) %></td>
            <td><%= user.email %></td>
            <td><%= user.phone_number %></td>
            <td><%= link_to "編集", edit_admins_user_path(user.id), class: "btn btn-primary" %></td>
            <td><%= link_to "削除", admins_user_path(user.id), method: :delete ,"data-confirm" => "会員を削除しますか？",class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </table>
  </div>

    <%= paginate @users %>
</main>

app/views/admins/users/show.html.erb
<main>
	<div class="container-fluid text-light">
			<div class="row user-title">
				<div class="col-3">
                    <h3><%= @user.last_name %>様情報</h3>
                        <h5 class="bg-light text-dark">名前</h5>
                            <%= full_name(@user) %>
                        <h5 class="bg-light text-dark mt-2">名(カナ)</h5>
                            <%= @user.last_name_kana+@user.first_name_kana %>
                        <h5 class="bg-light text-dark mt-2">郵便番号</h5>
                            <%= @user.post_number %>
                        <h5 class="bg-light text-dark mt-2">住所</h5>
                            <%= full_address(@user) %>
                        <h5 class="bg-light text-dark mt-2">電話番号</h5>
                            <%= @user.phone_number %>
                        <h5 class="bg-light text-dark mt-2">メールアドレス</h5>
                            <%= @user.email %><br>
                        <%= link_to "編集", edit_admins_user_path(@user.id), class: "btn btn-primary mt-4" %>
                </div>
                <div class="col-9">
                    <h3>購入履歴一覧</h3>
                    <table class="table table-bordered table-size" id="table-center" >
                        <tr class="bg-light text-dark">
                            <td>購入日</td>
                            <td>合計金額</td>
                            <td>送付先</td>
                            <td>ステータス</td>
                            <td>シングル/アルバム名</td>
                            <td>購入枚数</td>
                            <td>小計</td>
                        </tr>
                        <% @orders.each do |order|%>
                        <tr>
                            <td rowspan="<%= order.buy_products.count + 1 %>"><%= order.created_at.strftime('%Y年%m月%d日') %></td>
                            <td rowspan="<%= order.buy_products.count + 1 %>"><%= order_total(order) %></td>
                            <td rowspan="<%= order.buy_products.count + 1 %>"><%= order.shipping_address %></td>
                             <td rowspan="<%= order.buy_products.count + 1 %>"><%= order.shipping_status %></td>
                        </tr>
                           <% order.buy_products.each do |buy_product| %>
                                <tr>
                                    <td><%= buy_product.buy_title %></td>
                                    <td><%= buy_product.buy_number%><span>枚</span></td>
                                    <td><%= buy_product.buy_price * buy_product.buy_number%><span>円</span></td>
                                </tr>
                           <% end %>
                        <% end %>
                    </table>
                </div>
          </div>
	</div>
</main>