config/routes.rb
Rails.application.routes.draw do

devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
   sessions:      'users/sessions',
   passwords:     'users/passwords',
   registrations: 'users/registrations'
}
	root 'users/products#top'
	get '/admins/top', to:'admins/products#top'
	get '/users', to:'users#show', as:'users'
	get '/order/set_address', to:'users/orders#set_address'
	get '/order/confirmation/:shipping_address_id', to:'users/orders#new', as:'order_confirmation'
	post '/order', to:'users/orders#create'
	get '/order/complete', to:'users/orders#show'
	get '/order_address/new', to:'users/shipping_addresses#new_when_order'
	post '/order_address', to:'users/shipping_addresses#create_when_order'
	get 'search', to: 'products#search', as: :search
	post '/admins/products/new/artist_create', to: 'admins/products#artist_create'
	post '/admins/products/new/label_create', to: 'admins/products#label_create'
	post '/admins/products/new/category_create', to: 'admins/products#category_create'
	post '/admins/products/new/create', to: 'admins/products#create'
	# patch '/admins/products/new/artist_update', to: 'admins/products#artist_update'
	# patch '/admins/products/new/label_update', to: 'admins/products#label_update'
	# patch '/admins/products/new/category_update', to: 'admins/products#category_update'
	# patch '/admins/products/new/update', to: 'admins/products#update'
	# post '/users/products', to:'carts#create'
	namespace :users do
		resources :shipping_addresses
		resources :products, only: [:index, :show]
		get 'search', to: 'products#search'
	end
	resources :carts, only: [:index, :create, :update, :destroy]
	namespace :admins do
		resources :users, only: [:index, :show, :edit ,:update, :destroy]
		resources :products
		resources :orders, only: [:index, :update]
	end

	devise_scope :user do
    	get 'cart/sign_in/:product_id/:number', to: 'users/sessions#new'
  	end
end

app/models/cart.rb
class Cart < ApplicationRecord

	attachment :jacket_image


	belongs_to :user
	belongs_to :product

	def sum_of_price
    product.price * number
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

before_action :authenticate_user!, except: [:create]

 def index
 	 @user = User.find(current_user.id)
 	 @carts = Cart.where(user_id: current_user.id)
 end

 def update
 	 cart = Cart.find(params[:id])
 	 cart.update(cart_params)
 	 redirect_to carts_path
 end

 def create
    if current_user != nil
        @product = Product.find(params[:cart][:product_id])
        @cart = Cart.find_by(product_id: @product, user_id: current_user.id)
        if @cart.present?
            @cart.number = @cart.number + params[:cart][:number].to_i
            @cart.save
            redirect_to carts_path
        else
            @cart = Cart.new(cart_params)
            @cart.user_id = current_user.id
            @cart.save
            redirect_to carts_path
        end
    else
        redirect_to "/cart/sign_in/#{params[:cart][:product_id]}/#{params[:cart][:number]}"
    end
 end

 def destroy
 	 cart = Cart.find(params[:id])
 	 cart.delete
 	 redirect_to carts_path
 end

 private
	def cart_params
		params.require(:cart).permit(:number, :product_id)
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<main role="main" class="flex-shrink-0">
	<div class="container text-light">
	<div class="bg-light text-dark p-2 cart-title mb-3"><h3>カート</h3></div>
	<% flash.each do |key, value| %>
		<%= content_tag :div, value, class: "flash flash-#{key} text-warning" %>
	<% end %>
	<% @carts.each do |cart| %>
		<%= form_for(cart) do |f| %>
			<div class="row mt-3 pb-4 border-bottom">
				<div class="col-3 text-center">
					<%= attachment_image_tag cart.product, :jacket_image,fallback: "no_image.png", size: '100x100' %>
				</div>
				<div class="col-5 row">
					<div class="col-6">
						<h5><%= cart.product.title %></h5>
						<p><%= cart.product.artist.artist_name %></p>
						<h5><%= cart.product.price %> 円</h5>
					</div>
					<div class="col-6 d-flex align-items-center">
						数量 <%= f.number_field :number, value: cart.number, in: 1...cart.product.stock %>
						<%= f.submit '数量変更', class:"ml-4" %>
					</div>
				</div>
				<div class="col-2 d-flex align-items-center">
					小計：<%= cart.sum_of_price %> 円
				</div>
				<div class="col-2 d-flex align-items-center">
					<%= link_to "削除", cart_path(cart.id), method: :delete,"data-confirm" => "カートから削除しますか？", class: "btn-sm btn-danger", data: {"turbolinks" => false} %>
				</div>
			</div>
		<% end %>
	<% end %>
	<div class="row mt-5 mb-5">
		<div class="col-7">
			<%= link_to "お買い物を続ける", root_path, class: "btn-lg btn-primary", data: {"turbolinks" => false} %>
		</div>
		<% if @carts.empty? %>
			<h4>カートに商品がありません。</h4>
		<% else %>
			<div class="col-3">
				<h4 class="ml-5">合計： <%= cart_total(@carts) %> 円</h4>
			</div>
			<div class="col-2">
				<%= link_to "次に進む", order_set_address_path, class: "btn-lg btn-success", data: {"turbolinks" => false} %>
			</div>
		<% end %>
	</div>
</main>